/* ------------------------------------------------------------------
   RITUALS. Real steps, household materials, built-in substitutions.
   needs: tags checked against what she has. flame/bath: adapted.
------------------------------------------------------------------ */
const R = [
/* The 7-Day Energy Reset: seven days, seven voices of the circle */
{id:"whisper-sweep",g:"lily",reset:1,title:"The Whisper Sweep",el:"Air",moon:"Waning",min:10,
 purpose:"Disperse the residue of thought loops, arguments and old narratives.",
 needs:[["broom","A broom, a branch, or your open hand"]],
 steps:[
  {t:"Open the way",d:"Open a door or a window. Air needs somewhere to go."},
  {t:"Whisper",d:"Hold the broom close. Whisper into the bristles what you are removing. Overthinking. Fear of being seen. The old story. Name each one."},
  {t:"Sweep",d:"Sweep counterclockwise, moving toward the exit. No broom? Sweep the air with your open hand, the same direction, the same intent.",hold:60},
  {t:"Blow it out",d:"At the threshold, blow out once, hard.",say:"I return what is not mine. I dissolve what no longer serves."},
  {t:"Close",d:"Close the door. Stand still for three breaths before you do anything else."}],
 secret:"Air carries what is spoken low. This is not cleaning. This is dispersal.",
 prompts:["What did you whisper into the broom?","Which one was hardest to say out loud?"],
 tags:["overthinking","anxious","loop","stuck","heavy","reset"]},
{id:"salt-vein",g:"fern",reset:2,title:"Salt Vein Dissolve",el:"Water",moon:"Last Quarter",min:8,
 purpose:"Cut the cords and emotional drains you cannot see.",
 needs:[["salt","A spoonful of salt"],["bowl","A glass or bowl of warm water"]],
 steps:[
  {t:"Prepare the water",d:"Fill a glass or bowl with warm water. Add a spoonful of salt."},
  {t:"Stir",d:"Stir clockwise with your index finger while you speak softly.",say:"What flows to me returns cleansed. What clings, dissolves.",hold:45},
  {t:"Offer a signature",d:"Drop in a strand of your hair, or a pinch of any herb from your kitchen that you touched first."},
  {t:"Let it sit",d:"Leave it under moonlight, or near a window overnight."},
  {t:"Release",d:"In the morning, pour it down the drain. Do not look back at it."}],
 secret:"Hair and salt are both body signatures. You are sending out a coded severance.",
 prompts:["Who or what have you been leaking energy to?","What did you feel when you poured it out?"],
 tags:["drained","cord","ex","tired","cling","attached","reset"]},
{id:"wick-binding",g:"sage",reset:3,title:"Wick Binding",el:"Fire",moon:"Waxing Crescent",min:12,flame:true,
 purpose:"Gather your scattered will back into one thread.",
 needs:[["candle","A candle or tea light"],["thread","Cotton thread or string"]],
 steps:[
  {t:"Mark the candle",d:"Carve your initials into the candle with a pin or toothpick. With a tea light, write them on a paper wrap.",
   alt:{noFlame:"Write your initials on a small stone or on paper wrapped around a stone."}},
  {t:"Bind",d:"Tie a cotton thread around the base. Knot it three times."},
  {t:"Light and speak",d:"Light it. While it burns, speak.",say:"Let every fragmented flame return. Let my will be gathered. Let my work begin.",
   alt:{noFlame:"Set the stone in direct sunlight or under your brightest lamp. Hold your palms over it and speak."},hold:120},
  {t:"Snuff halfway",d:"Snuff it when it is about halfway down. Never leave a flame alone.",
   alt:{noFlame:"After two minutes, take the stone out of the light."}},
  {t:"Carry it",d:"Carry the stub or the stone with you for the rest of the week. It is your power token."}],
 secret:"This is fragment binding. Sympathetic flame and thread magic.",
 prompts:["Where has your energy been scattered?","What is the one thing you are gathering it back for?"],
 tags:["scattered","power","motivation","will","courage","reset"]},
{id:"rootprint",g:"thistle",reset:4,title:"Rootprint Activation",el:"Earth",moon:"First Quarter",min:7,
 purpose:"Reconnect with ancestral protection and your own body.",
 needs:[],
 steps:[
  {t:"Bare feet",d:"Go barefoot, on dirt if you can, on the floor if you can't."},
  {t:"Remember",d:"Hands on your thighs. Close your eyes. Whisper the names of the women and guardians, known or unknown, who walked before you.",hold:60},
  {t:"Stomp",d:"Stand. Stomp one foot three times.",say:"I stand in what I am. I carry what I choose."},
  {t:"Press down",d:"Press your palms to the earth or the floor and hold.",hold:30}],
 secret:"Footprints are signatures. You are tracing your lineage and claiming your space.",
 prompts:["Whose names came to you?","What are you choosing to carry, and what are you setting down?"],
 tags:["ungrounded","floaty","ancestors","body","anxious","reset"]},
{id:"obscured-mirror",g:"onyx",reset:5,title:"Obscured Mirror Water",el:"Moon",moon:"Waxing Gibbous",min:15,
 purpose:"Reach lunar intuition by blurring the ego's reflection.",
 needs:[["bowl","A dark bowl of water"],["milk","A drop of milk or ink"]],
 steps:[
  {t:"Cloud the water",d:"Pour water into a dark bowl. Add a single drop of milk or ink."},
  {t:"Soft gaze",d:"By low light, gaze into it. Do not focus. Let the surface move.",hold:120},
  {t:"Ask",d:"Ask out loud.",say:"What do I need to see that I have refused?"},
  {t:"Record",d:"Write down every image or impression, even the ones that make no sense yet."},
  {t:"Seal",d:"Fold the page closed and put it somewhere dark. You will read it again later."}],
 secret:"The clouded surface distorts your reflection so you get past the ego. This thins the veil.",
 prompts:["What did you see?","What have you been refusing to look at?"],
 tags:["intuition","confused","truth","denial","shadow","reset"]},
{id:"bone-bath",g:"juniper",reset:6,title:"Bone Bath",el:"Water and Earth",moon:"Waning Gibbous",min:20,bath:true,
 purpose:"Draw exhaustion out of the body, especially burnout and swallowed feeling.",
 needs:[["salt","Salt"],["vinegar","A splash of vinegar"],["eggs","Crushed eggshell, or rosemary"]],
 steps:[
  {t:"Draw the water",d:"Run a warm bath. Add a handful of salt, a splash of vinegar and crushed eggshell or rosemary.",
   alt:{noBath:"Fill a basin or pot for a foot soak. Add a pinch of salt, a splash of vinegar and crushed eggshell or rosemary."}},
  {t:"Speak before you enter",d:"Stand at the edge.",say:"What has calcified, I soften. What I carried, I now shed."},
  {t:"Soak in silence",d:"No phone. No music. Let the water do the talking.",hold:600},
  {t:"Pour it away",d:"When you are done, pour the water onto soil or let it drain with finality. Rinse off in clean water."}],
 secret:"Eggshell and vinegar speak to what is stored in bone. This cleanses the root of fatigue, not just the muscles.",
 prompts:["Where in your body were you holding it?","What softened?"],
 tags:["exhausted","burnout","body","tired","heavy","reset"]},
{id:"circle-sealing",g:"aura",reset:7,title:"Circle of Sealing",el:"All elements",moon:"Dark Moon",min:12,flame:true,
 purpose:"Close the portal. Contain what you gathered this week.",
 needs:[["candle","A candle, or any light"],["bowl","A glass of water"],["salt","A stone or pinch of salt"]],
 steps:[
  {t:"Place the elements",d:"In four corners of a small space, place one token each. Air: a feather, incense or a bell. Fire: a candle. Water: a glass. Earth: a stone or salt.",
   alt:{noFlame:"Use a lamp or a phone flashlight for Fire."}},
  {t:"Stand in the center",d:"Stand in the middle of what you built.",say:"I return to myself. Sealed. Witnessed. Whole."},
  {t:"Clap once",d:"Clap your hands once, sharply. Put out the light."},
  {t:"Sit",d:"Sit in silence. You are done.",hold:120}],
 secret:"A personal circle casting. The four directions hold it, and sound seals it.",
 prompts:["What did this week change?","What will you keep doing?"],
 tags:["closure","complete","whole","reset"]},

/* The library. Aura reaches in here so you never have to browse. */
{id:"burned-word",g:"sage",title:"The Burned Word",el:"Fire",moon:"Waning",min:8,flame:true,
 purpose:"Discharge anger that keeps replaying.",
 needs:[["candle","A lighter or candle and a fireproof bowl"]],
 steps:[
  {t:"Write it raw",d:"Write it all down. Every name. Every word you swallowed. Do not edit, do not be fair."},
  {t:"Read it once",d:"Read it out loud, once, at full volume if you can."},
  {t:"Burn it",d:"Over the bowl, light a corner and let it burn down completely.",
   alt:{noFlame:"Tear it into the smallest pieces you can and drown them in a bowl of water."}},
  {t:"Claim the fire",d:"Watch it go.",say:"This fire is mine. What it burns does not come back."},
  {t:"Cold water",d:"Wash your hands in cold water. Done means done."}],
 secret:"Anger is fuel, not a home. You are converting it, not suppressing it.",
 prompts:["What did you say that you have never said before?","How does your body feel now?"],
 tags:["angry","pissed","rage","mad","furious","betrayed","resent","unfair"]},
{id:"unsent-letter",g:"onyx",title:"The Unsent Letter",el:"Shadow",moon:"Waning Crescent",min:15,
 purpose:"Tell the truth you keep swallowing, without having to send it.",
 needs:[],
 steps:[
  {t:"Choose who",d:"Write to the person, or the old version of you, who never got the truth."},
  {t:"Write the line you keep deleting",d:"There is one sentence you keep editing out. Write that one first."},
  {t:"Underline",d:"Read it back. Underline the line that hurts."},
  {t:"Fold away",d:"Fold the page away from you three times.",say:"I told the truth. I don't have to send it for it to be true."},
  {t:"Put it in the dark",d:"Keep it somewhere dark for one full moon cycle. Then decide."}],
 secret:"Shame lives in what stays unsaid. Writing it moves it from inside you to outside you.",
 prompts:["What was the line you kept deleting?","What changes if you stop protecting them from it?"],
 tags:["shame","guilt","truth","secret","grief","regret","hiding","ex","closure"]},
{id:"tidewater-rest",g:"fern",title:"Tidewater Rest",el:"Water",moon:"Any",min:12,
 purpose:"Permission to stop.",
 needs:[["bowl","A bowl of warm water"]],
 steps:[
  {t:"Warm water",d:"Fill a bowl with warm water. Rest both hands in it."},
  {t:"Breathe with it",d:"Ten slow breaths. Feel the water hold your hands.",hold:60},
  {t:"Permission",d:"Say it out loud, even if it feels untrue.",say:"I am allowed to stop."},
  {t:"Lie down",d:"Lie down with your eyes closed. Nothing to fix for five minutes.",hold:300},
  {t:"Return it",d:"Pour the water onto a plant or down the drain."}],
 secret:"Water carries what you cannot. Rest is not a reward. It is the ritual.",
 prompts:["What were you trying to hold up alone?","What can wait until tomorrow?"],
 tags:["tired","exhausted","overwhelmed","sad","cry","rest","sleep","drained","burnout","depleted"]},
{id:"four-count",g:"lily",title:"Four-Count Clearing",el:"Air",moon:"Any",min:5,
 purpose:"Quiet a racing mind fast.",
 needs:[],
 steps:[
  {t:"Open a window",d:"Open a window or step outside. Fresh air in."},
  {t:"Box breath",d:"In for four. Hold for four. Out for four. Hold for four. Four rounds.",hold:64},
  {t:"Wipe it clean",d:"Wipe a mirror or a window with a little water.",say:"Clear channel. Clear mind."},
  {t:"Name the next thing",d:"Say out loud the one thing that actually matters next. Only one."}],
 secret:"Breath is the only part of your nervous system you can steer by hand.",
 prompts:["What was the loudest thought?","What is the one next thing?"],
 tags:["anxious","anxiety","panic","overthinking","scattered","racing","nervous","foggy","worried","stress"]},
{id:"salt-line",g:"thistle",title:"The Salt Line",el:"Earth",moon:"Waning",min:7,
 purpose:"Draw a boundary you can see.",
 needs:[["salt","Salt"]],
 steps:[
  {t:"Stand at the door",d:"Go to your front door or the door of your room."},
  {t:"Name it",d:"Say out loud who or what is no longer allowed in. Be specific. This does not make you mean."},
  {t:"Draw the line",d:"Pour a thin line of salt along the threshold or windowsill. No salt? Trace the line with a wet finger."},
  {t:"Claim it",d:"Step back inside the line.",say:"This is my edge. What comes in, I invite."},
  {t:"Morning",d:"Leave it overnight. In the morning, sweep it out the door."}],
 secret:"Salt has marked edges for as long as people have had doors.",
 prompts:["Who did you name?","What will you say the next time they push?"],
 tags:["boundaries","boundary","people pleasing","family","say no","used","taken advantage","draining","protect"]},
{id:"mirror-honey",g:"marigold",title:"Mirror Honey",el:"Light",moon:"Waxing",min:6,
 purpose:"Speak to yourself the way you speak to the people you love.",
 needs:[["mirror","A mirror"],["honey","A little honey or sugar"]],
 steps:[
  {t:"Good light",d:"Stand at a mirror in the best light in your home."},
  {t:"Sweeten",d:"Touch a little honey to your lips."},
  {t:"Three truths",d:"Look yourself in the eye and say three things that are true about you. Then say them again, sweeter."},
  {t:"Claim it",d:"Hold your own gaze.",say:"I am worth the attention I give everyone else."},
  {t:"Wear the gold",d:"Put on one thing that makes you feel like gold. Earrings, lipstick, the good robe."}],
 secret:"Honey binds sweetness to whatever it touches. Here it touches your own words.",
 prompts:["Which truth was hardest to say?","What would you do today if you believed it?"],
 tags:["insecure","ugly","worth","confidence","unworthy","compare","self love","love myself","joy","money","abundance"]},
{id:"threshold-reset",g:"juniper",title:"Threshold Reset",el:"Wood",moon:"Any",min:15,
 purpose:"Clear a space that feels heavy or stale.",
 needs:[["rosemary","Rosemary, citrus peel or any fragrant herb"]],
 steps:[
  {t:"One surface",d:"Clear one surface completely. Just one."},
  {t:"Wipe with salt water",d:"Wipe it down with water and a pinch of salt."},
  {t:"Scent the air",d:"Simmer rosemary or citrus peel in a small pot. No stove handy? Pour hot water over them in a mug and let it steam."},
  {t:"Open and walk",d:"Open doors and windows. Walk the room clockwise.",say:"Clear the room. Clear the air.",hold:90},
  {t:"Place one thing",d:"Set one meaningful object back on the clean surface. On purpose."}],
 secret:"A space holds what happens in it. You are resetting the container.",
 prompts:["What did the space feel like before?","What do you want this room to hold now?"],
 tags:["house","home","room","space","clutter","stale","moved","move","new place","heavy energy","cleanse"]},
{id:"jar-returning",g:"rue",title:"Jar of Returning",el:"Warding",moon:"Waning",min:10,
 purpose:"Protection from someone's ill will, and sending it back where it came from.",
 needs:[["jar","A small jar with a lid"],["salt","Salt"],["pepper","Black pepper"]],
 steps:[
  {t:"Write the order",d:"On a small piece of paper, write: Returned to sender. No harm, no hold."},
  {t:"Fold away",d:"Fold it away from you twice."},
  {t:"Layer",d:"Salt first, then the paper, then pepper, then rosemary if you have it."},
  {t:"Seal and shake",d:"Close it tight and shake it hard.",say:"Block. Cut. Banish. Not in my house."},
  {t:"Place it",d:"Keep it by the front door or in a dark cupboard. Try me."}],
 secret:"A witch bottle is one of the oldest wards there is. Nothing about this is new. That's why it works.",
 prompts:["Whose energy are you returning?","How will you know it worked?"],
 tags:["jealous","jealousy","envy","enemy","against me","toxic","evil eye","hate","protection","gossip","hater"]},
{id:"ledger",g:"sol",title:"The Ledger of Intention",el:"Metal",moon:"New",min:10,
 purpose:"Turn a wish into three moves.",
 needs:[],
 steps:[
  {t:"Three intentions",d:"Write three intentions for this cycle. Plain words."},
  {t:"One move each",d:"Under each, write one action you could do in fifteen minutes."},
  {t:"Put it in the plan",d:"Put all three actions on your calendar right now. Dates and times."},
  {t:"Sign it",d:"Sign and date the page.",say:"Discipline is devotion."},
  {t:"Carry it",d:"Fold it and keep it with your keys or wallet until the next new moon."}],
 secret:"An intention without a time is a wish. A time turns it into a spell.",
 prompts:["Which intention scares you a little?","What is the first fifteen-minute move?"],
 tags:["stuck","procrastinate","plan","goals","focus","start","new beginning","discipline","job","career","motivation","lost"]},
{id:"seed-intention",g:"sol",title:"New Moon Seed",el:"Earth",moon:"New",min:10,
 purpose:"Plant one intention in something that actually grows.",
 needs:[["soil","A seed or dried bean and a cup of soil or damp paper towel"]],
 steps:[
  {t:"Hold the seed",d:"Hold a seed or a dried bean in your palm. Warm it."},
  {t:"Speak into it",d:"Say your intention into your closed hand, once, clearly."},
  {t:"Plant",d:"Press it into a cup of soil, or fold it into a damp paper towel in a jar."},
  {t:"Seal the promise",d:"Water it.",say:"I plant it. I tend it. I trust the dark to do its work."},
  {t:"Tend",d:"Water it every day. Every time you do, you are tending the intention."}],
 secret:"New moons are dark on purpose. Everything that grows starts where you can't see it.",
 prompts:["What did you plant?","What will tending it look like this week?"],
 tags:["new beginning","start","fresh start","hope","new","intention","beginning"]},
{id:"full-moon-release",g:"fern",title:"Full Moon Release Bowl",el:"Water",moon:"Full",min:15,
 purpose:"Let go of what you've outgrown while the light is strongest.",
 needs:[["bowl","A bowl of water"]],
 steps:[
  {t:"Write what is leaving",d:"On paper, write what is ready to leave you. A habit, a fear, a person's hold."},
  {t:"Moonlight",d:"Set a bowl of water where the moon can reach it, or at a window."},
  {t:"Tear and drop",d:"Tear the paper and drop the pieces in the water.",say:"I release what I have outgrown."},
  {t:"Sit with it",d:"Sit beside the bowl for a few minutes. Watch the ink soften.",hold:180},
  {t:"Pour it out",d:"In the morning, pour it onto soil or down the drain."}],
 secret:"The full moon pulls tides. You are letting her pull this too.",
 prompts:["What did you release?","What is making room for?"],
 tags:["let go","release","move on","breakup","outgrown","done","grief"]},
{id:"gilded-shower",g:"marigold",title:"The Gilded Shower",el:"Light",moon:"Any",min:20,bath:true,
 purpose:"Luxury as medicine.",
 needs:[["oil","Body oil, lotion or anything that smells like a treat"]],
 steps:[
  {t:"Set the scene",d:"Dim the lights. Something that smells good. The good towel, not the old one."},
  {t:"Wash it off",d:"In the water, name what you're washing off today, part by part.",
   alt:{noBath:"Use a warm washcloth at the sink. Neck, wrists, face, feet."},hold:300},
  {t:"Anoint",d:"Oil or lotion, slowly, on purpose, like you're worth the time.",say:"You're allowed."},
  {t:"Get dressed for you",d:"Put on something that makes you feel like the main character. Nobody has to see it."}],
 secret:"Pleasure is a frequency. You are tuning to it on purpose.",
 prompts:["What did you wash off?","When did you last treat yourself like this?"],
 tags:["ugly","worth","tired","treat","pamper","joy","confidence","self love","breakup"]},
{id:"anchor",g:"aura",title:"The Five-Minute Anchor",el:"All elements",moon:"Any",min:5,
 purpose:"When you don't know what you need yet.",
 needs:[],
 steps:[
  {t:"Hand on heart",d:"Put one hand on your chest. Feel it rise."},
  {t:"Name where you are",d:"Say it out loud: the day, where you are, and what you're carrying. No fixing, just naming."},
  {t:"Touch an element",d:"Touch one element. Water from the tap. Light from a window. A plant. The floor.",hold:30},
  {t:"Speak",d:"Breathe once, slowly.",say:"I am here. I can do the next small thing."},
  {t:"Choose",d:"Choose the next small thing. Do only that."}],
 secret:"You don't have to know what's wrong to come back to yourself.",
 prompts:["What are you actually carrying?","What is the next small thing?"],
 tags:["off","dont know","numb","weird","blah","lost","idk"]}
];
